import type { Metadata } from 'next';
import Header from '@/components/Header/Header';
import '@/styles/global.scss';
import { Fraunces, Nunito } from 'next/font/google';
import Footer from '@/components/Footer/Footer';
import styles from '@/app/page.module.scss';

const fraunces = Fraunces({
  subsets: ['latin'],
  variable: '--font-fraunces',
});

const nunito = Nunito({
  subsets: ['latin'],
  variable: '--font-nunito',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

//edit later...
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${fraunces.variable} ${nunito.variable}`}>
      <body>
        <Header />
        <main className={styles.main}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
