import type { Metadata } from 'next';
import { Fraunces, Nunito } from 'next/font/google';
import '@/styles/global.scss';

const fraunces = Fraunces({
  subsets: ['latin'],
  variable: '--font-fraunces',
});

const nunito = Nunito({
  subsets: ['latin'],
  variable: '--font-nunito',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

//edit later...
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${fraunces.variable} ${nunito.variable}`}>
      <body>{children}</body>
    </html>
  );
}
